### ISSUE TITLE
Fails on Ruby 3.3 with `lambda method requires a literal block`.

### ISSUE THREAD

**Issue by sengi** [alphagov/govuk_app_config#341]
This prevents consumers of govuk_app_config from building with Ruby 3.3 or above.

See [Kernel#lambda raises when passed Proc instance](https://rubyreferences.github.io/rubychanges/3.3.html#kernellambda-raises-when-passed-proc-instance) in the 3.3 release notes.

```
ArgumentError: the lambda method requires a literal block (ArgumentError)

    ::Kernel.instance_method(m).bind_call(self, *args, &block)
                                            ^^^^^^^^^^^^^^^^^^^
vendor/bundle/ruby/3.3.0/gems/govuk_app_config-9.8.1/lib/govuk_app_config/govuk_error/configuration.rb:88:in `ignore_excluded_exceptions_in_data_sync'
vendor/bundle/ruby/3.3.0/gems/govuk_app_config-9.8.1/lib/govuk_app_config/govuk_error/configuration.rb:70:in `set_up_defaults'
vendor/bundle/ruby/3.3.0/gems/govuk_app_config-9.8.1/lib/govuk_app_config/govuk_error/configuration.rb:12:in `initialize'
```

Repro: take pretty much any GOV.UK app (e.g. alphagov/release), update its .ruby-version to 3.3.0 and run the project's tests.

**Comment by sengi** [comment]
Thanks for taking a look at this @robinjam ❤️
